const _ = require('underscore')
const moment = require('moment')
const reports = require('../helpers/reports')
const excelBuilder = require('msexcel-builder')
const logger = require('@open-age/logger')('form-25')

const build = async (fileName, ofDate, getExtraHours, attendances, orgDetails) => {
    const log = logger.start('build')
    var workbook = excelBuilder.createWorkbook('./temp/', fileName)
    var totalEmployees = attendances.length
    var columnNo = 1
    var rowNo = 8
    var sheet1 = workbook.createSheet('Attendances', 100, totalEmployees * 15)
    var titleColumn = 1
    var serialNo = 1
    log.info('sheet1 created')

    sheet1.merge({ col: 1, row: 1 }, { col: 38, row: 2 })
    sheet1.width(1, 10)
    sheet1.font(1, 1, { bold: 'true', sz: '20' })
    sheet1.align(1, 1, 'center')
    sheet1.border(1, 1, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
    sheet1.fill(1, 1, { type: 'solid', fgColor: '8', bgColor: '64' })
    sheet1.set(1, 1, `${orgDetails.orgName.toUpperCase()}`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Serial No In System`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 35.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'top')
    sheet1.align(titleColumn, 7, 'center')
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Name & Residential Address`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 35.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'top')
    sheet1.align(titleColumn, 7, 'center')
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Fathers/Husband Name`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 20.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'top')
    sheet1.align(titleColumn, 7, 'center')
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Cerifying Surgeons Certification No./Code`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 20.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'top')
    sheet1.align(titleColumn, 7, 'center')
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Provident Fund No.`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 20.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'top')
    sheet1.align(titleColumn, 7, 'center')
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Insurance No`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 20.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'top')
    sheet1.align(titleColumn, 7, 'center')
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Designation`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 20.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 7, 'top')
    sheet1.align(titleColumn, 7, 'center')
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Nature Of Work`)

    log.info('creating dates as per dates in month')
    for (var day = 1; day <= moment(ofDate).daysInMonth(); day++) {
        sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn + 1, row: 6 })
        sheet1.width(titleColumn, 8.0)
        sheet1.font(titleColumn, 6, { sz: '10' })
        sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', bottom: 'thin' })
        sheet1.border(titleColumn + 1, 6, { top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.align(titleColumn, 6, 'center')
        sheet1.set(titleColumn, 6, `${day}`)

        for (var i = 1; i <= 2; i++) {
            sheet1.width(titleColumn, 4.0)
            sheet1.font(titleColumn, 7, { sz: '10' })
            sheet1.border(titleColumn, 7, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
            sheet1.valign(titleColumn, 7, 'center')
            sheet1.rotate(titleColumn, 7, 90)
            sheet1.set(titleColumn++, 7, i === 1 ? `1st Period` : `2nd Period`)
        }
    }
    log.info('dates creared')

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Days Actually Worked`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Weekly Holidays Earned`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Casual Leaves`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Earned Leaves`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Accident Or Sick Leave`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Leave Without Pay`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 4.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Total Days Absent`)

    sheet1.merge({ col: titleColumn, row: 6 }, { col: titleColumn, row: 7 })
    sheet1.width(titleColumn, 12.0)
    sheet1.font(titleColumn, 6, { sz: '10' })
    sheet1.valign(titleColumn, 6, 'center')
    sheet1.rotate(titleColumn, 6, 90)
    sheet1.border(titleColumn, 6, { left: 'thin', top: 'thin', right: 'thin' })
    sheet1.border(titleColumn, 7, { left: 'thin', bottom: 'thin', right: 'thin' })
    sheet1.set(titleColumn++, 6, `Remarks`)

    log.info('starting injecting data into sheet1')
    await Promise.each(attendances, data => {
        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${serialNo++}`)

        sheet1.width(columnNo, 25.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${data.employee.name}`)
        sheet1.width(columnNo, 35.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${'NA'}`)
        sheet1.width(columnNo, 20.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${data.employee.code}`)
        sheet1.width(columnNo, 20.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${'NA'}`)
        sheet1.width(columnNo, 20.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${'NA'}`)
        sheet1.width(columnNo, 20.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${data.employee.designation}`)
        sheet1.width(columnNo, 20.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'left')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${'NA'}`)
        log.info(`processing form-25 of ${data.employee.name}`)
        for (var date = 1; date <= moment(ofDate).daysInMonth(); date++) {
            let attendance = null
            if (data.monthLog && data.monthLog.attendances.length) {
                attendance = reports.getAttendanceByOfDate(date, data.monthLog.attendances)
            }
            if (attendance) {
                if (!attendance.shift || !attendance.shift.status) {
                    sheet1.width(columnNo, 4.0)
                    sheet1.font(columnNo, rowNo, { sz: '10' })
                    sheet1.align(columnNo, rowNo, 'center')
                    sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                    sheet1.set(columnNo++, rowNo, `${attendance.status.charAt(0).toUpperCase() || 'NA'}`)

                    sheet1.width(columnNo, 4.0)
                    sheet1.font(columnNo, rowNo, { sz: '10' })
                    sheet1.align(columnNo, rowNo, 'center')
                    sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                    sheet1.set(columnNo++, rowNo, `${attendance.status.charAt(0).toUpperCase() || 'NA'}`)
                } else if (attendance.shift.status === 'working') {
                    sheet1.width(columnNo, 4.0)
                    sheet1.font(columnNo, rowNo, { sz: '10' })
                    sheet1.align(columnNo, rowNo, 'center')
                    sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                    sheet1.set(columnNo++, rowNo, `${attendance.status.charAt(0).toUpperCase() || 'NA'}`)

                    sheet1.width(columnNo, 4.0)
                    sheet1.font(columnNo, rowNo, { sz: '10' })
                    sheet1.align(columnNo, rowNo, 'center')
                    sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                    sheet1.set(columnNo++, rowNo, `${attendance.status.charAt(0).toUpperCase() || 'NA'}`)
                } else {
                    sheet1.width(columnNo, 4.0)
                    sheet1.font(columnNo, rowNo, { sz: '10' })
                    sheet1.align(columnNo, rowNo, 'center')
                    sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                    sheet1.set(columnNo++, rowNo, `${attendance.shift.status.charAt(0).toUpperCase() || 'NA'}`)

                    sheet1.width(columnNo, 4.0)
                    sheet1.font(columnNo, rowNo, { sz: '10' })
                    sheet1.align(columnNo, rowNo, 'center')
                    sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                    sheet1.set(columnNo++, rowNo, `${attendance.shift.status.charAt(0).toUpperCase() || 'NA'}`)
                }
            } else {
                sheet1.width(columnNo, 4.0)
                sheet1.font(columnNo, rowNo, { sz: '10' })
                sheet1.align(columnNo, rowNo, 'center')
                sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                sheet1.set(columnNo++, rowNo, `NA`)

                sheet1.width(columnNo, 4.0)
                sheet1.font(columnNo, rowNo, { sz: '10' })
                sheet1.align(columnNo, rowNo, 'center')
                sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
                sheet1.set(columnNo++, rowNo, `NA`)
            }
        }
        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${data.monthLog ? data.monthLog.attendanceCount : 0}`)

        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, ` `)

        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, ` `)

        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, ` `)

        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, ` `)

        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, ` `)

        sheet1.width(columnNo, 4.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, `${data.monthLog ? moment(ofDate).daysInMonth() - data.monthLog.attendanceCount : 0}`)

        sheet1.width(columnNo, 12.0)
        sheet1.font(columnNo, rowNo, { sz: '10' })
        sheet1.align(columnNo, rowNo, 'center')
        sheet1.border(columnNo, rowNo, { left: 'thin', top: 'thin', right: 'thin', bottom: 'thin' })
        sheet1.set(columnNo++, rowNo, ` `)

        columnNo = 1
        rowNo = rowNo + 2
    })

    return new Promise((resolve, reject) => {
        workbook.save(function (err) {
            if (!err) {
                log.info('congratulations, your workbook created')
                return resolve({
                    isCreated: true,
                    message: 'attendance sheet successfully created'
                })
            }
            workbook.cancel()
            return reject(new Error('attendance sheet not created'))
        })
    })
}

exports.build = build
